version: 2.1
defaults: &defaults
  docker:
    - image: circleci/python:3.7.2
jobs:
  build-image:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching:
      - run:
          name: Build Docker image with GH tag as tag
          command: |
            tag=${CIRCLE_TAG}
            docker build -t jasongriffin/circleci-playground:$tag .

workflows:
  version: 2
  publish-version:
    jobs:
      - build-image:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
