version: 2.1
defaults: &defaults
  docker:
    - image: vampio/kmt:circleci-latest
jobs:
  build-push-image:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image tagged with GH tag
          command: |
            if [ ! -z ${DOCKER_PUBLISH_IMAGE+x} ]; then
              service=$CIRCLE_PROJECT_REPONAME
              tag="${CIRCLE_TAG:1}"
              docker build -t $DOCKER_ORG/$service:$tag .
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker push $DOCKER_ORG/$service:$tag
            fi
  update-rp-sava-cart-204-pt-prod:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Update sava-cart-2.0.4 with pt-production finished
          command: |
            python3 bin/update-release-plan.py \
              --release-plan release-plans/sava-cart-2.0.4.json \
              --environment-name pt-production \
              --release-status finished

workflows:
  version: 2
  publish-version:
    jobs:
      - build-push-image:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
