version: 2.1
defaults: &defaults
  docker:
    - image: circleci/python:3.7.2
jobs:
  build-image:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching:
      - run:
          name: Build Docker image with GH tag as tag
          command: |
            tag="${CIRCLE_TAG:1}"
            docker build -t $DOCKER_ORG/circleci-playground:$tag .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push $DOCKER_ORG/circleci-playground:$tag
      - run:
          name: Clone repo
          command: |
            git clone https://github.com/jason-magnetic-io/vamp-kmt-examples.git
      - run:
          name: Update service def with new version
          command: |
            service_def=vamp-kmt-examples/tutorial5/services/sava-product/sava-product.json
            tag="${CIRCLE_TAG:1}"
            python3 vamp-kmt-examples/circleci/version-update/update_version.py -f $service_def -t $tag
            cat $service_def
      - run:
          name: Configure git
          command: |
            git config user.email "jason@magnetic.io"
            git config user.name "circleci"
      - add_ssh_keys:
          fingerprints:
            - "68:e9:39:38:a9:73:a7:bd:05:dc:20:4e:a5:e2:9a:1c"
      - run:
          name: Push new version
          command: |
            tag="${CIRCLE_TAG:1}"
            cd vamp-kmt-examples
            git add .
            git commit -m "Added version ${tag}"
            git push

workflows:
  version: 2
  publish-version:
    jobs:
      - build-image:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
